### ISSUE TITLE
Contributing guidelines

### ISSUE THREAD

**Issue by JesseSwildens** [JesseSwildens/Software-ontwikkeling-VESOFTON#16]
**Is your feature request related to a problem? Please describe.**
Currently there are only verbal agreements what the contributing guidelines are. Make this into a document so this project has strictly defined rules to follow so the quality of the documentation and code is the same throughout the different contributes.

**Describe the solution you'd like**
Make a readme for the contributions guidelines.

**Comment by tomseli** [comment]
TODO: After #13, add a TLDR naming convention
