### ISSUE TITLE
Last line of the text file does not get send in terminal

### ISSUE THREAD

**Issue by Mirkoet** [JesseSwildens/Software-ontwikkeling-VESOFTON#50]
**Describe the bug**
When sending all lines at once in the terminal it does not send the last sentence in the text file

**To Reproduce**
1. load a text file
2. press send all
3. notice it wont send nor echo

**Comment by tomseli** [comment]
Fixed: 

![image](https://github.com/JesseSwildens/Software-ontwikkeling-VESOFTON/assets/91960714/e7c7bfc7-20f9-4e34-8648-5d8a611f9c9d)
