### ISSUE TITLE
Improve doxygen style using theme

### ISSUE THREAD

**Issue by JesseSwildens** [JesseSwildens/Software-ontwikkeling-VESOFTON#62]
**Is your feature request related to a problem? Please describe.**
As a developer I want to make the doxygen stand out so it isn’t in the default style

**Describe the solution you'd like**
Use a theme to import styling to the docs

**Additional context**
E.g. https://github.com/kcwongjoe/doxygen_theme_flat_design

**Comment by tomseli** [comment]
https://jothepro.github.io/doxygen-awesome-css/
